name: CI/CD GitHub Actions
on: [push]
jobs:
  pytest-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pygame
          
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Coveralls
        run: |
            pip install coveralls
            coverage run -m pytest tests/
            coveralls

#   sonarcloud:
#     needs: pytest-tests
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python }}
#       - name: Install tox and any other packages
#         run: pip install tox
#       - name: Run tox
#         run: tox -e py
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
