name: CI/CD GitHub Actions
on: [push]
jobs:
  pytest-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pygame
          
      - name: Test with pytest
        run: |
          python -m pytest
#     steps:
#         uses: actions/checkout@v2, actions/setup-python@v4
#         with:
#           python-version: '3.9' # install the python version needed
#         run: |
#           python -m pip install --upgrade pip
#           python tests/test_cloud.py

#- name: Coveralls
#        run: coveralls -t ${{ secrets.coveralls_token }} --root . -E ".*external.*" -E ".*tests.*"
